name: Deploy to Skynet

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: yarn
      - run: yarn build
        env:
          NEXT_PUBLIC_PAY_TOKEN_SYMBOL: fDAI
          NEXT_PUBLIC_BICONOMY_ENABLED: "true"
          NEXT_PUBLIC_MUMBAI_BICONOMY_API_KEY: ${{ secrets.MUMBAI_BICONOMY_API_KEY }}
          NEXT_PUBLIC_KOVAN_BICONOMY_API_KEY: ${{ secrets.KOVAN_BICONOMY_API_KEY }}
          NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
      - run: yarn next export

      - name: "Deploy to Skynet"
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: out
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}
