name: Deploy to Skynet

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: yarn
      - run: yarn build
      - run: yarn next export
        env:
          NEXT_PUBLIC_PAY_TOKEN_SYMBOL: fDAI
          NEXT_PUBLIC_BICONOMY_ENABLED: true
          NEXT_PUBLIC_BICONOMY_API_KEY: ${{ secrets.BICONOMY_API_KEY }}

      - name: "Deploy to Skynet"
        uses: SkynetLabs/deploy-to-skynet-action@v2
        with:
          upload-dir: out
          github-token: ${{ secrets.GITHUB_TOKEN }}
          registry-seed: ${{ secrets.SKYNET_REGISTRY_SEED || '' }}
